### ISSUE TITLE
Cannot press b on the chat

### ISSUE THREAD

**Issue by LemTheLemon** [videoerror/SurvivalTest-M0d#2]
Pressing b on the chat sends text to the chat, very weird bug!

**Comment by videoerror** [comment]
Thank you, will be testing this out and trying to fix this by next release.

**Comment by videoerror** [comment]
This is not a bug but is due to you using ClassicalSharp dev builds instead of ClassicalSharp release builds. The most affected thing when mismatching releases and dev builds is keybinds. This is fairly common and is not due to my code. Release builds can be found here: https://github.com/UnknownShadow200/ClassicalSharp/releases/
