### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wDFran** [videoerror/SurvivalTest-M0d#3]
Hi, when i try to open any of the 2 versions, i get the following error
![0fcc2819caabd5c3fb3647cd5d80500b](https://cloud.githubusercontent.com/assets/25127788/21959887/f5569cc8-dab3-11e6-89ab-4d9c98e40385.png)

**Comment by videoerror** [comment]
It seems to not be able to find the .NET Framework. Do you have the .NET framework installed unto your computer? Have you used ClassicalSharp client in the past? If so I have no idea how you where using it. Furthermore I suggust using the DirectX build if your on Windows rather than the OpenGL build. OpenGL is compatible with all systems but DirectX will probably be better for WIndows.

**Comment by wDFran** [comment]
I got  NET Framework 3.5, and yes, i have used the ClassicalSharp client .

**Comment by videoerror** [comment]
Have you installed the mod correctly? To install the new release please place the exe file in your ClassicalSharp installation folder, deleting the old "ClassicalSharp.exe"(Or moving it to a different location for when you'd like to switch back to the vanilla client) and renaming "SurvivalTest_M0d-PR0T0TYPE-0_DirectX.exe" or "SurvivalTest_M0d-PR0T0TYPE-0_OpenGL.exe" to "ClassicalSharp.exe" so it is recognizable by the launcher.

**Comment by wDFran** [comment]
Oh, ok, thank you :D

**Comment by videoerror** [comment]
No problem! =D Did you get it working properly? If so I'd like to close this issue.

**Comment by wDFran** [comment]
Yes
